services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: incident-api-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: incident_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init-postgis.sql:/docker-entrypoint-initdb.d/init-postgis.sql

volumes:
  postgres_data:
